
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 152
#define YY_END_OF_BUFFER 153
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[356] =
    {   0,
        0,    0,  142,  142,    0,    0,    0,    0,  153,  151,
      148,  150,  149,  151,  147,   32,   37,   40,   35,   23,
       34,   24,   39,   41,   41,   22,   38,   33,   26,   29,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   30,   36,  142,  144,  143,   91,
       89,   48,   90,   91,   88,   80,   83,   47,   44,   71,
       45,   72,   46,   70,   84,   81,   74,   77,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   78,   82,  139,  137,   96,  138,  139,  136,
      128,  131,   95,   92,  119,   93,  120,   94,  118,  132,

      129,  122,  125,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  126,  130,   27,
      147,  146,    0,   41,    0,    0,   41,   25,    0,    0,
      141,    0,    0,   41,   21,   31,   28,   20,   20,   20,
       20,   16,   20,   20,   20,    2,   12,   20,   20,    5,
       18,   20,   20,   20,   20,   20,  142,  143,  143,  145,
       75,   88,   87,   73,   86,    0,   69,   79,   76,   68,
       68,   68,   68,   64,   68,   68,   68,   50,   60,   68,
       68,   53,   66,   68,   68,   68,   68,   68,  123,  136,
      135,  121,  134,    0,  117,  127,  124,  116,  116,  116,

      116,  112,  116,  116,  116,   98,  108,  116,  116,  101,
      114,  116,  116,  116,  116,  116,    0,   41,    0,   43,
        0,  140,  140,   42,   19,   20,   20,   20,   11,   20,
       20,   17,   20,   20,   20,    3,   20,    0,   85,   85,
       67,   68,   68,   68,   59,   68,   68,   65,   68,   68,
       68,   51,   68,    0,  133,  133,  115,  116,  116,  116,
      107,  116,  116,  113,  116,  116,  116,   99,  116,   42,
       20,   20,   14,   20,   20,   20,   20,    7,   13,   20,
       68,   68,   62,   68,   68,   68,   68,   55,   61,   68,
      116,  116,  110,  116,  116,  116,  116,  103,  109,  116,

        4,   10,   20,   20,   20,   20,   15,   52,   58,   68,
       68,   68,   68,   63,  100,  106,  116,  116,  116,  116,
      111,   20,   20,   20,   20,   68,   68,   68,   68,  116,
      116,  116,  116,   20,    6,   20,    1,   68,   54,   68,
       49,  116,  102,  116,   97,    8,   20,   56,   68,  104,
      116,    9,   57,  105,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    1,    1,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   18,   19,
       20,   21,    1,    1,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   31,   32,   33,   34,   35,   36,
       31,   37,   38,   39,   40,   41,   42,   31,   43,   31,
       44,    1,   45,    1,   46,    1,   22,   23,   24,   25,

       26,   27,   28,   29,   30,   31,   31,   32,   33,   34,
       35,   36,   31,   37,   38,   39,   40,   41,   42,   31,
       43,   31,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[47] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    4,    4,    1,    1,    1,    1,
        1,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    1,    1,    4
    } ;

static yyconst flex_int16_t yy_base[368] =
    {   0,
        0,    0,   44,   45,   54,    0,  100,    0,  466,  467,
      467,  467,  467,  445,  458,  467,  467,  467,   34,  467,
      134,  138,  143,  143,  147,  443,  467,  442,  467,  441,
      131,  434,    0,  424,  138,  418,  149,  422,  134,  419,
      429,  425,  431,  423,  467,  467,    0,  467,  166,  467,
      467,  467,  467,  431,  444,  467,  467,  467,  467,  467,
      467,  436,  168,  428,  467,  427,  467,  426,  144,  419,
        0,  409,  152,  403,  160,  407,  152,  404,  414,  410,
      416,  408,  467,  467,  467,  467,  467,  467,  416,  429,
      467,  467,  467,  467,  467,  467,  421,  179,  413,  467,

      412,  467,  411,  158,  404,    0,  394,  164,  388,  172,
      392,  163,  389,  399,  395,  401,  393,  467,  467,  467,
      415,  467,  188,  192,  194,  198,  206,  467,  200,  213,
      467,   48,  215,  220,  467,  467,  467,    0,  395,  382,
      390,    0,  379,  391,  381,    0,    0,  375,  374,    0,
        0,  377,  389,  384,  372,  378,    0,  203,  225,  467,
      467,  401,  467,  467,  467,  163,  467,  467,  467,    0,
      381,  368,  376,    0,  365,  377,  367,    0,    0,  361,
      360,    0,    0,  363,  375,  370,  358,  364,  467,  387,
      467,  467,  467,  234,  467,  467,  467,    0,  367,  354,

      362,    0,  351,  363,  353,    0,    0,  347,  346,    0,
        0,  349,  361,  356,  344,  350,  227,  232,  234,  236,
      250,  467,  252,  244,    0,  357,  348,  351,    0,  352,
      349,    0,  216,  342,  339,    0,  340,  258,  467,  260,
        0,  349,  340,  343,    0,  344,  341,    0,  241,  334,
      331,    0,  332,  263,  467,  268,    0,  341,  332,  335,
        0,  336,  333,    0,  249,  326,  323,    0,  324,  259,
      312,  320,    0,  314,  324,  325,  313,    0,    0,  323,
      305,  313,    0,  307,  317,  318,  306,    0,    0,  316,
      298,  306,    0,  300,  310,  311,  299,    0,    0,  309,

        0,    0,  304,  307,  307,  309,    0,    0,    0,  300,
      303,  303,  305,    0,    0,    0,  296,  299,  299,  301,
        0,  287,  284,  280,  286,  283,  280,  276,  282,  279,
      262,  255,  258,  254,    0,  250,    0,  249,    0,  239,
        0,  234,    0,  220,    0,    0,  201,    0,  198,    0,
      176,    0,    0,    0,  467,  277,  281,  187,  285,  289,
      293,  151,  297,  144,  301,  305,  309
    } ;

static yyconst flex_int16_t yy_def[368] =
    {   0,
      355,    1,  356,  356,  355,    5,  355,    7,  355,  355,
      355,  355,  355,  355,  357,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  355,  355,  359,  355,  360,  355,
      355,  355,  355,  355,  361,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  355,  355,  355,  355,  355,  355,  355,  363,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,

      355,  355,  355,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  355,  355,  355,
      357,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  365,  355,  355,  355,  355,  355,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  359,  360,  360,  355,
      355,  361,  355,  355,  355,  366,  355,  355,  355,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  355,  363,
      355,  355,  355,  367,  355,  355,  355,  364,  364,  364,

      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  355,  355,  355,  355,
      365,  355,  365,  355,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  366,  355,  366,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  367,  355,  367,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  355,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,

      358,  358,  358,  358,  358,  358,  358,  362,  362,  362,
      362,  362,  362,  362,  364,  364,  364,  364,  364,  364,
      364,  358,  358,  358,  358,  362,  362,  362,  362,  364,
      364,  364,  364,  358,  358,  358,  358,  362,  362,  362,
      362,  364,  364,  364,  364,  358,  358,  362,  362,  364,
      364,  358,  362,  364,    0,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355
    } ;

static yyconst flex_int16_t yy_nxt[514] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   33,   33,   37,
       33,   33,   33,   38,   39,   40,   41,   33,   42,   33,
       43,   44,   33,   45,   46,   10,   48,   48,  123,  124,
      222,  223,   49,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   58,   59,   60,   61,   62,   63,   50,   50,
       64,   65,   66,   67,   68,   69,   70,   71,   72,   73,
       74,   71,   71,   75,   71,   71,   71,   76,   77,   78,
       79,   71,   80,   71,   81,   82,   71,   83,   84,   50,

       85,   86,   87,   88,   89,   90,   91,   92,   93,   94,
       95,   96,   97,   98,   85,   85,   99,  100,  101,  102,
      103,  104,  105,  106,  107,  108,  109,  106,  106,  110,
      106,  106,  106,  111,  112,  113,  114,  106,  115,  106,
      116,  117,  106,  118,  119,   85,  125,  198,  126,  127,
      128,  131,  129,  129,  170,  133,  132,  126,  126,  133,
      150,  134,  134,  130,  139,  239,  240,  140,  130,  143,
      151,  144,  130,  146,  159,  147,  165,  171,  182,  160,
      172,  166,  148,  175,  178,  176,  179,  193,  183,  210,
      138,  199,  194,  180,  200,  203,  206,  204,  207,  211,

      217,  354,  123,  123,  217,  208,  218,  218,  129,  129,
      133,  355,  126,  126,  129,  129,  355,  130,  133,  130,
      134,  134,  219,  353,  219,  130,  352,  220,  220,  224,
      224,  130,  133,  159,  134,  134,  255,  256,  355,  276,
      130,  270,  270,  277,  217,  130,  218,  218,  220,  220,
      220,  220,  222,  223,  222,  223,  351,  130,  224,  224,
      239,  240,  239,  240,  286,  255,  256,  350,  287,  130,
      255,  256,  296,  270,  270,  349,  297,   47,   47,   47,
       47,  121,  348,  121,  121,  157,  347,  346,  157,  158,
      345,  158,  158,  162,  344,  162,  162,  190,  343,  190,

      190,  221,  221,  221,  221,  238,  238,  238,  238,  254,
      254,  254,  254,  342,  341,  340,  339,  338,  337,  336,
      335,  334,  333,  332,  331,  330,  329,  328,  327,  326,
      325,  324,  323,  322,  321,  320,  319,  318,  317,  316,
      315,  314,  313,  312,  311,  310,  309,  308,  307,  306,
      305,  304,  303,  302,  301,  300,  299,  298,  295,  294,
      293,  292,  291,  290,  289,  288,  285,  284,  283,  282,
      281,  280,  279,  278,  275,  274,  273,  272,  271,  269,
      268,  267,  266,  265,  264,  263,  262,  261,  260,  259,
      258,  257,  191,  253,  252,  251,  250,  249,  248,  247,

      246,  245,  244,  243,  242,  241,  163,  237,  236,  235,
      234,  233,  232,  231,  230,  229,  228,  227,  226,  225,
      122,  216,  215,  214,  213,  212,  209,  205,  202,  201,
      197,  196,  195,  192,  191,  189,  188,  187,  186,  185,
      184,  181,  177,  174,  173,  169,  168,  167,  164,  163,
      161,  156,  155,  154,  153,  152,  149,  145,  142,  141,
      137,  136,  135,  122,  120,  355,    9,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,

      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355
    } ;

static yyconst flex_int16_t yy_chk[514] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    4,   19,   19,
      132,  132,    3,    4,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,   21,  364,   21,   21,
       22,   23,   22,   22,  362,   24,   23,   24,   24,   25,
       39,   25,   25,   22,   31,  166,  166,   31,   24,   35,
       39,   35,   25,   37,   49,   37,   63,   69,   77,   49,
       69,   63,   37,   73,   75,   73,   75,   98,   77,  112,
      358,  104,   98,   75,  104,  108,  110,  108,  110,  112,

      123,  351,  123,  123,  124,  110,  124,  124,  125,  125,
      126,  158,  126,  126,  129,  129,  158,  124,  127,  125,
      127,  127,  130,  349,  130,  129,  347,  130,  130,  133,
      133,  127,  134,  159,  134,  134,  194,  194,  159,  233,
      133,  217,  217,  233,  218,  134,  218,  218,  219,  219,
      220,  220,  221,  221,  223,  223,  344,  218,  224,  224,
      238,  238,  240,  240,  249,  254,  254,  342,  249,  224,
      256,  256,  265,  270,  270,  340,  265,  356,  356,  356,
      356,  357,  338,  357,  357,  359,  336,  334,  359,  360,
      333,  360,  360,  361,  332,  361,  361,  363,  331,  363,

      363,  365,  365,  365,  365,  366,  366,  366,  366,  367,
      367,  367,  367,  330,  329,  328,  327,  326,  325,  324,
      323,  322,  320,  319,  318,  317,  313,  312,  311,  310,
      306,  305,  304,  303,  300,  297,  296,  295,  294,  292,
      291,  290,  287,  286,  285,  284,  282,  281,  280,  277,
      276,  275,  274,  272,  271,  269,  267,  266,  263,  262,
      260,  259,  258,  253,  251,  250,  247,  246,  244,  243,
      242,  237,  235,  234,  231,  230,  228,  227,  226,  216,
      215,  214,  213,  212,  209,  208,  205,  204,  203,  201,
      200,  199,  190,  188,  187,  186,  185,  184,  181,  180,

      177,  176,  175,  173,  172,  171,  162,  156,  155,  154,
      153,  152,  149,  148,  145,  144,  143,  141,  140,  139,
      121,  117,  116,  115,  114,  113,  111,  109,  107,  105,
      103,  101,   99,   97,   90,   89,   82,   81,   80,   79,
       78,   76,   74,   72,   70,   68,   66,   64,   62,   55,
       54,   44,   43,   42,   41,   40,   38,   36,   34,   32,
       30,   28,   26,   15,   14,    9,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,

      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 2 "lex.l"
#include <string.h>
#include "y.tab.h"
// #define   PROGRAM      1
// #define   IDENTIFIER      2
// #define   LPAREN      3
// #define   RPAREN      4
// #define   SEMICOLON      5
// #define   DOT      6
// #define   COMMA      7
// #define   VAR      8
// #define   COLON      9
// #define   ARRAY      10
// #define   RBRAC      11
// #define   LBRAC      12
// #define   NUM    13
// #define   STRINGCONSTANT 14
// #define   OF       16
// #define   INTEGER               17
// #define   REAL                  18
// #define   FUNCTION      19
// #define   PROCEDURE      20
// #define   PBEGIN      21
// #define   END     22
// #define   ASSIGNMENT      23
// #define   IF      24
// #define   THEN      25
// #define   ELSE      26
// #define   WHILE      27
// #define   DO      28
// #define   GE      29
// #define   GT      30
// #define   LE      31
// #define   LT      32
// #define   EQUAL      33
// #define   MINUS      34
// #define   notEQUAL    35
// #define   PLUS      36
// #define   SLASH      37
// #define   STAR      38
// #define   NOT      39
// #define   DOTDOT      40
// #define   COMMENT     41
// #define   AND     42
// #define   OR    43

int line_no = 1;
int i=0;




#line 734 "lex.yy.c"

#define INITIAL 0
#define COMMENTSPACE 1
#define PLUSSPACE 2
#define IDSPACE 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 82 "lex.l"


#line 922 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 356 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 467 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 84 "lex.l"
return(PROGRAM);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 85 "lex.l"
return(IDENTIFIER);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 86 "lex.l"
return(VAR);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 87 "lex.l"
return(ARRAY);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 88 "lex.l"
return(OF);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 89 "lex.l"
return(INTEGER);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 90 "lex.l"
return(REAL);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 91 "lex.l"
return(FUNCTION);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 92 "lex.l"
return(PROCEDURE);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 93 "lex.l"
return(PBEGIN);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 94 "lex.l"
return(END);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 95 "lex.l"
return(IF);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 96 "lex.l"
return(THEN);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 97 "lex.l"
return(ELSE);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 98 "lex.l"
return(WHILE);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 99 "lex.l"
return(DO);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 100 "lex.l"
return(NOT);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 101 "lex.l"
return(OR);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 102 "lex.l"
return(AND);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 103 "lex.l"
{BEGIN IDSPACE; return(IDENTIFIER);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 105 "lex.l"
return(ASSIGNMENT);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 106 "lex.l"
return(COLON);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 107 "lex.l"
return(COMMA);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 108 "lex.l"
return(DOT);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 109 "lex.l"
return(DOTDOT);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 110 "lex.l"
return(EQUAL);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 111 "lex.l"
return(notEQUAL);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 112 "lex.l"
return(GE);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 113 "lex.l"
return(GT);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 114 "lex.l"
return(LBRAC);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 115 "lex.l"
return(LE);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 116 "lex.l"
return(LPAREN);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 117 "lex.l"
return(LT);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 118 "lex.l"
return(MINUS);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 119 "lex.l"
return(PLUS);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 120 "lex.l"
return(RBRAC);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 121 "lex.l"
return(RPAREN);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 122 "lex.l"
return(SEMICOLON);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 123 "lex.l"
return(SLASH);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 124 "lex.l"
return(STAR);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 125 "lex.l"
{BEGIN PLUSSPACE;return(NUM);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 126 "lex.l"
{BEGIN PLUSSPACE;return(NUM);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 127 "lex.l"
{BEGIN PLUSSPACE;return(NUM);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 129 "lex.l"
{BEGIN 0;return(PLUS);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 130 "lex.l"
{BEGIN 0;return(MINUS);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 131 "lex.l"
{BEGIN 0;return(SLASH);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 132 "lex.l"
{BEGIN 0;return(STAR);}
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 133 "lex.l"
{++line_no; BEGIN 0;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 134 "lex.l"
{BEGIN 0;return(PROGRAM);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 135 "lex.l"
{BEGIN 0;return(IDENTIFIER);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 136 "lex.l"
{BEGIN 0;return(VAR);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 137 "lex.l"
{BEGIN 0;return(ARRAY);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 138 "lex.l"
{BEGIN 0;return(OF);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 139 "lex.l"
{BEGIN 0;return(INTEGER);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 140 "lex.l"
{BEGIN 0;return(REAL);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 141 "lex.l"
{BEGIN 0;return(FUNCTION);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 142 "lex.l"
{BEGIN 0;return(PROCEDURE);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 143 "lex.l"
{BEGIN 0;return(PBEGIN);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 144 "lex.l"
{BEGIN 0;return(END);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 145 "lex.l"
{BEGIN 0;return(IF);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 146 "lex.l"
{BEGIN 0;return(THEN);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 147 "lex.l"
{BEGIN 0;return(ELSE);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 148 "lex.l"
{BEGIN 0;return(WHILE);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 149 "lex.l"
{BEGIN 0;return(DO);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 150 "lex.l"
{BEGIN 0;return(NOT);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 151 "lex.l"
{BEGIN 0;return(OR);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 152 "lex.l"
{BEGIN 0;return(AND);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 153 "lex.l"
{BEGIN 0;return(IDENTIFIER);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 154 "lex.l"
{BEGIN 0;return(ASSIGNMENT);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 155 "lex.l"
{BEGIN 0;return(COLON);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 156 "lex.l"
{BEGIN 0;return(COMMA);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 157 "lex.l"
{BEGIN 0;return(DOT);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 158 "lex.l"
{BEGIN 0;return(DOTDOT);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 159 "lex.l"
{BEGIN 0;return(EQUAL);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 160 "lex.l"
{BEGIN 0;return(notEQUAL);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 161 "lex.l"
{BEGIN 0;return(GE);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 162 "lex.l"
{BEGIN 0;return(GT);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 163 "lex.l"
{BEGIN 0;return(LBRAC);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 164 "lex.l"
{BEGIN 0;return(LE);}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 165 "lex.l"
{BEGIN 0;return(LPAREN);}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 166 "lex.l"
{BEGIN 0;return(LT);}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 167 "lex.l"
{BEGIN 0;return(RBRAC);}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 168 "lex.l"
{BEGIN 0;return(RPAREN);}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 169 "lex.l"
{BEGIN 0;return(SEMICOLON);}
	YY_BREAK
case 85:
/* rule 85 can match eol */
YY_RULE_SETUP
#line 170 "lex.l"
{
                                        i++;
                                        line_no++;
                                        BEGIN 0;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 174 "lex.l"
{
                                        BEGIN COMMENTSPACE;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 176 "lex.l"
{BEGIN 0;return (STRINGCONSTANT);}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 177 "lex.l"
{BEGIN 0;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 178 "lex.l"
{}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 179 "lex.l"
{BEGIN 0;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 180 "lex.l"
{BEGIN 0;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 182 "lex.l"
{BEGIN 0;return(PLUS);}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 183 "lex.l"
{BEGIN 0;return(MINUS);}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 184 "lex.l"
{BEGIN 0;return(SLASH);}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 185 "lex.l"
{BEGIN 0;return(STAR);}
	YY_BREAK
case 96:
/* rule 96 can match eol */
YY_RULE_SETUP
#line 186 "lex.l"
{++line_no; BEGIN 0;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 187 "lex.l"
{BEGIN 0;return(PROGRAM);}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 188 "lex.l"
{BEGIN 0;return(IDENTIFIER);}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 189 "lex.l"
{BEGIN 0;return(VAR);}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 190 "lex.l"
{BEGIN 0;return(ARRAY);}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 191 "lex.l"
{BEGIN 0;return(OF);}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 192 "lex.l"
{BEGIN 0;return(INTEGER);}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 193 "lex.l"
{BEGIN 0;return(REAL);}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 194 "lex.l"
{BEGIN 0;return(FUNCTION);}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 195 "lex.l"
{BEGIN 0;return(PROCEDURE);}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 196 "lex.l"
{BEGIN 0;return(PBEGIN);}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 197 "lex.l"
{BEGIN 0;return(END);}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 198 "lex.l"
{BEGIN 0;return(IF);}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 199 "lex.l"
{BEGIN 0;return(THEN);}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 200 "lex.l"
{BEGIN 0;return(ELSE);}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 201 "lex.l"
{BEGIN 0;return(WHILE);}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 202 "lex.l"
{BEGIN 0;return(DO);}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 203 "lex.l"
{BEGIN 0;return(NOT);}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 204 "lex.l"
{BEGIN 0;return(OR);}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 205 "lex.l"
{BEGIN 0;return(AND);}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 206 "lex.l"
{BEGIN 0;return(IDENTIFIER);}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 207 "lex.l"
{BEGIN 0;return(ASSIGNMENT);}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 208 "lex.l"
{BEGIN 0;return(COLON);}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 209 "lex.l"
{BEGIN 0;return(COMMA);}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 210 "lex.l"
{BEGIN 0;return(DOT);}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 211 "lex.l"
{BEGIN 0;return(DOTDOT);}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 212 "lex.l"
{BEGIN 0;return(EQUAL);}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 213 "lex.l"
{BEGIN 0;return(notEQUAL);}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 214 "lex.l"
{BEGIN 0;return(GE);}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 215 "lex.l"
{BEGIN 0;return(GT);}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 216 "lex.l"
{BEGIN 0;return(LBRAC);}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 217 "lex.l"
{BEGIN 0;return(LE);}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 218 "lex.l"
{BEGIN 0;return(LPAREN);}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 219 "lex.l"
{BEGIN 0;return(LT);}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 220 "lex.l"
{BEGIN 0;return(RBRAC);}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 221 "lex.l"
{BEGIN 0;return(RPAREN);}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 222 "lex.l"
{BEGIN 0;return(SEMICOLON);}
	YY_BREAK
case 133:
/* rule 133 can match eol */
YY_RULE_SETUP
#line 223 "lex.l"
{
                                        i++;
                                        line_no++;
                                        BEGIN 0;}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 227 "lex.l"
{BEGIN COMMENTSPACE;}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 228 "lex.l"
{BEGIN 0;return (STRINGCONSTANT);}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 229 "lex.l"
{BEGIN 0;}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 230 "lex.l"
{}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 231 "lex.l"
{BEGIN 0;}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 232 "lex.l"
{BEGIN 0;}
	YY_BREAK
case 140:
/* rule 140 can match eol */
YY_RULE_SETUP
#line 235 "lex.l"
{
                i++;
                line_no++;
              }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 239 "lex.l"
{BEGIN COMMENTSPACE;}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 240 "lex.l"
{}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 241 "lex.l"
{}
	YY_BREAK
case 144:
/* rule 144 can match eol */
YY_RULE_SETUP
#line 242 "lex.l"
{ ++line_no;}
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 243 "lex.l"
{BEGIN 0;} 
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 245 "lex.l"
return (STRINGCONSTANT);
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 246 "lex.l"
{ }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 248 "lex.l"
;
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 250 "lex.l"
;
	YY_BREAK
case 150:
/* rule 150 can match eol */
YY_RULE_SETUP
#line 251 "lex.l"
{
    line_no++;
  } 
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 255 "lex.l"
{fprintf(stderr,"",line_no,yytext);
       }
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 258 "lex.l"
ECHO;
	YY_BREAK
#line 1785 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENTSPACE):
case YY_STATE_EOF(PLUSSPACE):
case YY_STATE_EOF(IDSPACE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 356 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 356 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 355);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 258 "lex.l"



int main1(int argc, char** argv) {
  int tok;
  yyin = fopen("test.txt", "r");
  for (i = 0; 1==1; i ++) {
    tok = yylex();
    fprintf(stderr, "%3d-th token(type:%d) on line %d : %s\n", i, tok,line_no, yytext);
  }
  return(0);
} /* end of main */

